apiVersion: v1
kind: Service
metadata:
  name: inferenceforge-gateway
  labels:
    app: inferenceforge-gateway
    app.kubernetes.io/name: inferenceforge
spec:
  selector:
    app: inferenceforge-gateway
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.gateway.port }}
  type: {{ if .Values.ingress.enabled }}ClusterIP{{ else }}LoadBalancer{{ end }}
