apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceforge-config
data:
  # Local (Ollama)
  model_backend_url: "http://inferenceforge-model:11434"
  model_name: "tinyllama"
  backend_type: "ollama"

  # GPU / vLLM — update these values when deploying to EKS:
  # model_backend_url: "http://inferenceforge-model:8000"
  # model_name: "mistralai/Mistral-7B-Instruct-v0.2"
  # backend_type: "vllm"
